### PR TITLE
Epic: Form builder compatibility 

### PR DESCRIPTION
**Pull request by alaca**
## Description

This PR adds compatibility with the Visual Donation Form Builder. [GIVE-477]

## Visuals

Screen Capture_select-area_20240401183526
Screen Capture_select-area_20240401184917

## Testing instructions
Create a new form and insert DTD block
View the form on the frontend
Select a company 
Make a donation

## Pre-review Checklist

-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-477]: https://stellarwp.atlassian.net/browse/GIVE-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@alaca is this ready for QA or are you still working on anything?

**Comment by alaca** [comment]
@jonwaldstein this is waiting for review. I assigned you as a reviewer since you already reviewed all PRs related to this. This is basically a collection of already approved PRs.

**Review by rickalday — APPROVED** [review]
Passed QA tests

**Comment by jonwaldstein** [comment]
@alaca FYI I scaffolded the unit test bootstrapping.  I'm going to add a few tests today and would like your help (if possible).  It's important to me that we have unit tests in place before releasing a major version update so we are more confident in the stability for our customers 😄

**Review by jonwaldstein — APPROVED** [review]
Given the demand for this feature, I will move this forward for release.  We can circle back to more unit tests in the near future.

**Pull request merged**
